### ISSUE TITLE
ASCII is missing

### ISSUE THREAD

**Issue by n0ah01** [Capuno/Farfetch#1]
For me the ASCII Art is not shown:

![screenshot](https://user-images.githubusercontent.com/7645313/35030696-454c87e2-fb60-11e7-9b93-85e1f3f6db30.png)

OS: Ubuntu 17.10
Shell: Bash
Terminal: Alacritty and Gnome Terminal

The config file is unchanged, so ascii is set to true.

Thank you for the help, its possible that I'm just to stupit... :D

**Comment by n0ah01** [comment]
![screenshot from 2018-01-17 09-07-48](https://user-images.githubusercontent.com/7645313/35032095-ecefb802-fb65-11e7-8b0c-0f4eab669222.png)

Thank you for the quick answer, I told you I was to stupid :-)

Would you mind if I commit some more ASCII art to get people startet more quickly? Maybe just puting them in one file, so the user can copy/past what they want...?

**Comment by Capuno** [comment]
Yea that would be awesome, I was thinking in making different files inside the build/ folder with different names like planets.ascii, debian.ascii etc. so the user could just change the name in the example settings.ini file.
Send a PR if you do some, but I'll be more active this weekend.
Thank you!

**Comment by n0ah01** [comment]
Great, thank you for the oportunity!
