### ISSUE TITLE
Color of the CPU label is taken from the ASCII art

### ISSUE THREAD

**Issue by n0ah01** [Capuno/Farfetch#3]
The Color of the CPU label is not taken from the settings (as for Kernel, Packages...), but seams to 'blend over' from the ASCII Art on the left side. See the screenshot for clarification.

![screenshot from 2018-01-17 14-34-40](https://user-images.githubusercontent.com/7645313/35045430-1d1fea3c-fb94-11e7-84da-b10fac47b47f.png)
 
Let me know if you need aditional info ;-)

**Comment by Capuno** [comment]
I fixed this in last commit with the temporal colors eab474bd11c2a34c1d70787c0f8995bc1fff6172 . I will be moving the text colors inside the settings.ini file in next commit.

**Comment by Capuno** [comment]
23b480745eb68f637114cab559ace8c8fcbd574a closes this issue
