### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by TheStilbruch** [Capuno/Farfetch#6]
After a normal install on Arch Linux, I get a segmentation fault when attempting to run.
Here is the exact error:
```
[1] 1488 segmentation fault (core dumped)  ff
```

**Comment by Capuno** [comment]
I can't replicate this issue on a virtual machine with Arch, did the `make` / `make install` give you any errors or warnings? What is your output for `ldd ~/bin/ff`?
